In [1]:
import tensorflow as tf
import numpy as np
import gym
import copy

from itertools import chain

from pddl2env import PddlBasicEnv
from stable_baselines.base_models_sp import BaseRLModel, SetVerbosity
import stable_baselines.tf_util as tf_util
from stable_baselines.replay_buffer import ReplayBuffer, EpisodicBuffer, her_future, HerFutureAchievedPastActual

/h/spitis/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
env = PddlBasicEnv(
      domain='pddl_files/modded_transport/domain.pddl',
      instance='pddl_files/modded_transport/ptest.pddl')

In [3]:
env.reset()

array([ 1,  9, 11, 12], dtype=int32)

In [4]:
def random_trajectory(env):
  state = env.reset()
  for i in range (10000):
    actions = env.get_actions()
    action = actions[np.random.choice(len(actions))]
    next_state, reward, done, _ = env.step(action)
    print(state, next_state, reward, done)
    if done: 
      break
    state = next_state    

In [8]:
env.E.state_to_emb(env.task.goals)

array([10, 13], dtype=int32)

In [14]:
int(env.task.goal_reached(env.task.initial_state))-1

-1

In [6]:
random_trajectory(env)

[ 1  9 11 12] [ 2  9 11 12] -1 0
[ 2  9 11 12] [ 2  5  8 12] -1 0
[ 2  5  8 12] [ 2  9 11 12] -1 0
[ 2  9 11 12] [ 1  9 11 12] -1 0
[ 1  9 11 12] [ 4  9 11 12] -1 0
[ 4  9 11 12] [4 5 7 9] -1 0
[4 5 7 9] [ 4  9 11 12] -1 0
[ 4  9 11 12] [4 5 7 9] -1 0
[4 5 7 9] [1 5 7 9] -1 0
[1 5 7 9] [4 5 7 9] -1 0
[4 5 7 9] [ 4  9 11 12] -1 0
[ 4  9 11 12] [4 5 7 9] -1 0
[4 5 7 9] [1 5 7 9] -1 0
[1 5 7 9] [2 5 7 9] -1 0
[2 5 7 9] [ 0  2  9 11] -1 0
[ 0  2  9 11] [0 2 5 8] -1 0
[0 2 5 8] [2 6 7 8] -1 0
[2 6 7 8] [2 5 7 9] -1 0
[2 5 7 9] [ 0  2  9 11] -1 0
[ 0  2  9 11] [ 0  1  9 11] -1 0
[ 0  1  9 11] [ 0  2  9 11] -1 0
[ 0  2  9 11] [ 0  1  9 11] -1 0
[ 0  1  9 11] [ 0  2  9 11] -1 0
[ 0  2  9 11] [2 5 7 9] -1 0
[2 5 7 9] [1 5 7 9] -1 0
[1 5 7 9] [4 5 7 9] -1 0
[4 5 7 9] [1 5 7 9] -1 0
[1 5 7 9] [2 5 7 9] -1 0
[2 5 7 9] [ 0  2  9 11] -1 0
[ 0  2  9 11] [ 0  1  9 11] -1 0
[ 0  1  9 11] [ 0  2  9 11] -1 0
[ 0  2  9 11] [ 0  1  9 11] -1 0
[ 0  1  9 11] [ 0  2  9 11] -1 0
[ 0  2  9 11] [2 5 7 9] -1 0
[2