In [1]:
import tensorflow as tf
import numpy as np
import gym
import copy

from itertools import chain

from pddl2env import PddlBasicEnv
from stable_baselines.base_models_sp import BaseRLModel, SetVerbosity
import stable_baselines.tf_util as tf_util
from stable_baselines.replay_buffer import ReplayBuffer, EpisodicBuffer, her_future, HerFutureAchievedPastActual

/h/spitis/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
env = PddlBasicEnv(
      domain='pddl_files/modded_transport/domain.pddl',
      instance='pddl_files/modded_transport/ptest.pddl')

In [8]:
env.reset()

array([ 2,  4,  7, 11], dtype=int32)

In [14]:
def random_trajectory(env):
  state = env.reset()
  for i in range (10000):
    actions = env.get_actions()
    action = actions[np.random.choice(len(actions))]
    next_state, reward, done, _ = env.step(action)
    print(state, next_state, reward, done)
    if done: 
      break
    state = next_state    

In [18]:
env.task.facts

{'(at package-1 city-loc-1)',
 '(at package-1 city-loc-2)',
 '(at package-1 city-loc-3)',
 '(at package-1 truck-1)',
 '(at package-2 city-loc-1)',
 '(at package-2 city-loc-2)',
 '(at package-2 city-loc-3)',
 '(at package-2 truck-1)',
 '(at truck-1 city-loc-1)',
 '(at truck-1 city-loc-2)',
 '(at truck-1 city-loc-3)',
 '(capacity truck-1 capacity-0)',
 '(capacity truck-1 capacity-1)',
 '(capacity truck-1 capacity-2)',
 '(capacity truck-1 capacity-3)',
 '(capacity truck-1 capacity-4)'}

In [17]:
random_trajectory(env)

[ 2  4  7 11] [ 2  7  8 11] -1 0
[ 2  7  8 11] [ 2  4  7 11] -1 0
[ 2  4  7 11] [ 1  2  7 11] -1 0
[ 1  2  7 11] [ 2  4  7 11] -1 0
[ 2  4  7 11] [ 2  7  8 11] -1 0
[ 2  7  8 11] [ 2  4  7 11] -1 0
[ 2  4  7 11] [ 2  7  8 11] -1 0
[ 2  7  8 11] [ 2  4  7 11] -1 0
[ 2  4  7 11] [ 1  2  7 11] -1 0
[ 1  2  7 11] [ 1  2  6 14] -1 0
[ 1  2  6 14] [ 1  2  7 11] -1 0
[ 1  2  7 11] [ 1  2  6 14] -1 0
[ 1  2  6 14] [ 2  4  6 14] -1 0
[ 2  4  6 14] [ 2  6  8 14] -1 0
[ 2  6  8 14] [ 2  4  6 14] -1 0
[ 2  4  6 14] [ 1  2  6 14] -1 0
[ 1  2  6 14] [ 2  4  6 14] -1 0
[ 2  4  6 14] [ 2  6  8 14] -1 0
[ 2  6  8 14] [ 2  5  8 11] -1 0
[ 2  5  8 11] [ 2  6  8 14] -1 0
[ 2  6  8 14] [ 2  5  8 11] -1 0
[ 2  5  8 11] [ 0  5  8 14] -1 0
[ 0  5  8 14] [ 0  4  5 14] -1 0
[ 0  4  5 14] [ 0  1  5 14] -1 0
[ 0  1  5 14] [ 0  4  5 14] -1 0
[ 0  4  5 14] [ 0  5  8 14] -1 0
[ 0  5  8 14] [ 0  4  5 14] -1 0
[ 0  4  5 14] [ 0  5  8 14] -1 0
[ 0  5  8 14] [0 3 6 8] -1 0
[0 3 6 8] [0 3 4 6] -1 0
[0 3 4 6] [0 1 3 6] -1